### ISSUE TITLE
nginx-rtmp на eric + скриптове за restreaming + запис

### ISSUE THREAD

**Issue by ignisf** [OpenFest/openfest-2015-network#8]

**Comment by krokodilerian** [comment]
Имаме вече nginx-rtmp инсталиран и един тестов скрипт в ~root/of2015/rtest.sh.

**Comment by krokodilerian** [comment]
Има два скрипта, rtest и rtest-hd, които трябва да са ок, само трябва да се пипнат имената на stream-овете.

**Comment by zeridon** [comment]
как може да се наглежда това?

**Comment by krokodilerian** [comment]
има /stats на nginx-а, в който се вижда по принцип всеки stream, ще направя един hostname там да има, че eric сочи на друг vhost

**Comment by krokodilerian** [comment]
http://eric-stream.openfest.org/stats

**Comment by zeridon** [comment]
имаме вече рудиментарно броене на броя стриймове

**Comment by zeridon** [comment]
closed by 014416ba108e504fbc1cab6b0b14911af7544a67
